#!/bin/bash
#
# Get LDAP Base DN from email domain
# Usage: get-base-dn.sh <username>
# Output: The LDAP base DN (e.g., dc=krea,dc=ac,dc=in)
#
# NOTE: This file is a TEMPLATE. The case statements below are 
# dynamically generated by init.sh from DOMAIN_CONFIG environment variable.
# DO NOT HARDCODE DOMAINS HERE - they will be overwritten on container restart.
#

USERNAME="$1"

# Extract domain from username (email)
DOMAIN=$(echo "$USERNAME" | sed 's/.*@//')

# Map domain to LDAP base DN
# --- BEGIN DYNAMIC DOMAIN MAPPING ---
case "$DOMAIN" in
    # This section is dynamically generated from DOMAIN_CONFIG
    # Placeholder entries - will be replaced by init.sh
    *)
        # Default fallback - uses BASE_DOMAIN and DOMAIN_EXTENSION from .env
        echo "dc=ENV_BASE_DOMAIN,dc=ENV_DOMAIN_EXTENSION"
        ;;
esac
# --- END DYNAMIC DOMAIN MAPPING ---
