#!/bin/sh
# ldap-auth.sh - External LDAP authentication for Google Workspace
# This bypasses FreeRADIUS LDAP module's DN escaping issue by doing LDAP bind directly
# Uses TLS client certificates for Google Workspace LDAP
#
# USAGE: Called from FreeRADIUS exec module in authorize/authenticate section
# Returns: 0 = success (Access-Accept), 1 = failure (Access-Reject)
#
# The domain to base_dn mapping is dynamically generated by init.sh
# from DOMAIN_CONFIG environment variable at container startup

# Arguments from FreeRADIUS exec module
USER_NAME="$1"
USER_PASSWORD="$2"

# LDAP Configuration for Google Workspace
LDAP_SERVER="ldaps://ldap.google.com:636"
LDAP_CLIENT_CERT="/etc/freeradius/certs/ldap-client.crt"
LDAP_CLIENT_KEY="/etc/freeradius/certs/ldap-client.key"

# Log for debugging
LOG_FILE="/var/log/freeradius/ldap-auth.log"

log_debug() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE" 2>/dev/null
}

# Validate input
if [ -z "$USER_NAME" ] || [ -z "$USER_PASSWORD" ]; then
    log_debug "Missing username or password"
    exit 1
fi

# Decode password if URL-encoded (GTC sends $ as =24, etc.)
# Also handle double encoding like =3D24
USER_PASSWORD=$(printf '%s' "$USER_PASSWORD" | sed 's/=3D24/$/g; s/=3D23/#/g; s/=3D26/\&/g; s/=3D40/@/g')
USER_PASSWORD=$(printf '%s' "$USER_PASSWORD" | sed 's/=24/$/g; s/=23/#/g; s/=26/\&/g; s/=40/@/g; s/=3D/=/g')

# Extract domain from email
DOMAIN=$(echo "$USER_NAME" | sed 's/.*@//')

# --- BEGIN DOMAIN TO BASE_DN MAPPING ---
# This section is dynamically generated by init.sh from DOMAIN_CONFIG
# Map domain to LDAP base DN
case "$DOMAIN" in
    "krea.ac.in")
        BASE_DN="dc=krea,dc=ac,dc=in"
        ;;
    "krea.edu.in")
        BASE_DN="dc=krea,dc=edu,dc=in"
        ;;
    "alumni.krea.edu.in")
        BASE_DN="dc=alumni,dc=krea,dc=edu,dc=in"
        ;;
    "ifmr.ac.in")
        BASE_DN="dc=ifmr,dc=ac,dc=in"
        ;;
    *)
        # Domain not configured
        log_debug "Unknown domain: $DOMAIN - not in DOMAIN_CONFIG"
        exit 1
        ;;
esac
# --- END DOMAIN TO BASE_DN MAPPING ---

log_debug "Auth attempt for user: $USER_NAME, domain: $DOMAIN, base_dn: $BASE_DN"

# Set up LDAP TLS environment for client certificate auth
export LDAPTLS_CERT="$LDAP_CLIENT_CERT"
export LDAPTLS_KEY="$LDAP_CLIENT_KEY"
export LDAPTLS_REQCERT="allow"

# Step 1: Search for the user DN using TLS client certificate authentication
# Google Workspace LDAP authenticates via client certificate for admin search
USER_DN=$(ldapsearch -H "$LDAP_SERVER" \
    -b "$BASE_DN" \
    -s sub \
    "(mail=$USER_NAME)" \
    -LLL \
    -o ldif-wrap=no \
    dn \
    2>/dev/null \
    | grep "^dn:" | head -1 | sed 's/^dn: //')

if [ -z "$USER_DN" ]; then
    log_debug "User not found in LDAP: $USER_NAME in base $BASE_DN"
    exit 1
fi

log_debug "Found user DN: $USER_DN"

# Step 2: Verify password by attempting to bind as the user
# Use password file approach to handle special characters properly
TMPPASS=$(mktemp)
printf '%s' "$USER_PASSWORD" > "$TMPPASS"
chmod 600 "$TMPPASS"

# Try to bind and search as the user - if bind succeeds, password is correct
BIND_RESULT=$(ldapsearch -H "$LDAP_SERVER" \
    -D "$USER_DN" \
    -x \
    -y "$TMPPASS" \
    -b "$USER_DN" \
    -s base \
    "(objectClass=*)" \
    dn 2>&1)

BIND_STATUS=$?

# Clean up temp password file
rm -f "$TMPPASS"

# Check bind result
if [ $BIND_STATUS -eq 0 ] && echo "$BIND_RESULT" | grep -q "^dn:"; then
    log_debug "Authentication successful for: $USER_NAME"
    # Exit 0 for success - do NOT output DN as FreeRADIUS will try to parse it
    exit 0
else
    log_debug "Authentication failed for: $USER_NAME - $BIND_RESULT"
    exit 1
fi
